/* Sproochentest Pro — Data (280 cards across 38 lessons) */
window.SPROOCHENTEST_DATA = {
lessons:[
{n:0,stars:3,title:"تواصل"},{n:1,stars:3,title:"Alphabet"},{n:2,stars:3,title:"Wou wunns du?"},
{n:3,stars:2,title:"Hunn/Sinn"},{n:4,stars:2,title:"Froewierder"},{n:5,stars:3,title:"Vu wou kënns du?"},
{n:6,stars:3,title:"N-Reegel"},{n:7,stars:3,title:"D'Auer"},{n:8,stars:2,title:"Déplacement"},
{n:9,stars:1,title:"Chrëschtdag"},{n:10,stars:3,title:"Adjectifs"},{n:11,stars:3,title:"Prononciation"},
{n:12,stars:3,title:"De Beruff"},{n:13,stars:2,title:"Imperativ"},{n:14,stars:2,title:"Plural"},
{n:15,stars:3,title:"Dokter"},{n:16,stars:3,title:"Possessifs"},{n:17,stars:3,title:"De Passé"},
{n:18,stars:2,title:"Mat Kanner"},{n:19,stars:2,title:"Adverbes"},{n:20,stars:3,title:"Akafen"},
{n:21,stars:3,title:"Futur"},{n:22,stars:3,title:"Akkusativ"},{n:23,stars:1,title:"Lieseck Têtelbierg"},
{n:24,stars:3,title:"Reesen"},{n:25,stars:2,title:"Kleeder"},{n:26,stars:3,title:"Exercicer I"},
{n:27,stars:3,title:"Conditionnel"},{n:28,stars:5,title:"Biller beschreiwen"},{n:29,stars:4,title:"D'Famill"},
{n:30,stars:1,title:"Lieseck Delarü"},{n:31,stars:2,title:"Impfungen"},{n:32,stars:2,title:"Modalverben"},
{n:33,stars:3,title:"Kachen"},{n:34,stars:3,title:"Exercicer II"},{n:35,stars:3,title:"Wieder"},
{n:36,stars:1,title:"Lieseck Melusina"},{n:37,stars:2,title:"Relativsätz"},{n:38,stars:2,title:"Auto"}
],
cards:[
// 0 — تواصل
{l:0,k:"p",lb:"Kënnt Dir dat widderhuelen?",fr:"Pouvez-vous répéter ?"},
{l:0,k:"p",lb:"Ech verstinn net ganz.",fr:"Je ne comprends pas"},
{l:0,k:"p",lb:"Kënnt Dir méi lues schwätzen?",fr:"Plus lentement ?"},
{l:0,k:"p",lb:"Ech hunn eng Fro...",fr:"J'ai une question..."},
{l:0,k:"p",lb:"Wéi seet een dat?",fr:"Comment dit-on ?"},
// 1 — Alphabet
{l:1,k:"v",lb:"Apel",fr:"pomme"},{l:1,k:"v",lb:"Bam",fr:"arbre"},
{l:1,k:"v",lb:"Dag",fr:"jour"},{l:1,k:"v",lb:"Fra",fr:"femme"},
{l:1,k:"v",lb:"Haus",fr:"maison"},{l:1,k:"v",lb:"Jong",fr:"garçon"},
{l:1,k:"v",lb:"Kand",fr:"enfant"},{l:1,k:"v",lb:"Mann",fr:"homme"},
{l:1,k:"v",lb:"Papp",fr:"père"},{l:1,k:"v",lb:"Waasser",fr:"eau"},
// 2 — Wou wunns du?
{l:2,k:"v",lb:"Däitschland",fr:"Allemagne"},{l:2,k:"v",lb:"Frankräich",fr:"France"},
{l:2,k:"v",lb:"Lëtzebuerg",fr:"Luxembourg"},{l:2,k:"v",lb:"Spuenien",fr:"Espagne"},
{l:2,k:"v",lb:"Däitsch",fr:"allemand"},{l:2,k:"v",lb:"Franséisch",fr:"français"},
{l:2,k:"p",lb:"Ech wunnen an Däitschland",fr:"J'habite en Allemagne"},
{l:2,k:"p",lb:"Ech wunnen zu Berlin",fr:"J'habite à Berlin"},
// 3 — Hunn/Sinn
{l:3,k:"v",lb:"den Hond",fr:"le chien"},{l:3,k:"v",lb:"d'Kaz",fr:"le chat"},
{l:3,k:"v",lb:"d'Buch",fr:"le livre"},{l:3,k:"g",lb:"ech hunn",fr:"j'ai"},
{l:3,k:"g",lb:"du hues",fr:"tu as"},{l:3,k:"g",lb:"hien huet",fr:"il a"},
{l:3,k:"g",lb:"ech sinn",fr:"je suis"},{l:3,k:"g",lb:"du bass",fr:"tu es"},
{l:3,k:"p",lb:"Ech sinn Architekt",fr:"Je suis architecte"},
{l:3,k:"p",lb:"Du hues e Kand",fr:"Tu as un enfant"},
// 4 — Froewierder
{l:4,k:"g",lb:"Wou?",fr:"Où ?"},{l:4,k:"g",lb:"Wat?",fr:"Quoi ?"},
{l:4,k:"g",lb:"Wéi?",fr:"Comment ?"},{l:4,k:"g",lb:"Wien?",fr:"Qui ?"},
{l:4,k:"g",lb:"Wéini?",fr:"Quand ?"},{l:4,k:"g",lb:"Firwat?",fr:"Pourquoi ?"},
{l:4,k:"g",lb:"Wéi vill?",fr:"Combien ?"},{l:4,k:"g",lb:"net",fr:"ne...pas"},
// 5 — Vu wou kënns du?
{l:5,k:"v",lb:"wunnen",fr:"habiter"},{l:5,k:"v",lb:"spillen",fr:"jouer"},
{l:5,k:"v",lb:"schaffen",fr:"travailler"},{l:5,k:"v",lb:"kachen",fr:"cuisiner"},
{l:5,k:"v",lb:"schwätzen",fr:"parler"},{l:5,k:"g",lb:"aus + pays",fr:"de + pays"},
{l:5,k:"p",lb:"Ech kommen aus Däitschland",fr:"Je viens d'Allemagne"},
{l:5,k:"p",lb:"Ech komme vu Berlin",fr:"Je viens de Berlin"},
// 6 — N-Reegel
{l:6,k:"g",lb:"N-Reegel",fr:"n devant a,e,i,o,u,n,d,t,z,h"},
{l:6,k:"g",lb:"Ech si frou",fr:"(sans n)"},{l:6,k:"g",lb:"Ech sinn nervös",fr:"(avec n)"},
{l:6,k:"v",lb:"een/eng",fr:"un/une"},{l:6,k:"v",lb:"zwee/zwou",fr:"deux"},
{l:6,k:"v",lb:"dräi",fr:"trois"},{l:6,k:"v",lb:"véier",fr:"quatre"},
{l:6,k:"v",lb:"fënnef",fr:"cinq"},{l:6,k:"v",lb:"zéng",fr:"dix"},
{l:6,k:"v",lb:"honnert",fr:"cent"},{l:6,k:"v",lb:"dausend",fr:"mille"},
// 7 — D'Auer
{l:7,k:"v",lb:"eng Auer",fr:"1 heure"},{l:7,k:"v",lb:"zwou Auer",fr:"2 heures"},
{l:7,k:"v",lb:"Mëtteg",fr:"midi"},{l:7,k:"v",lb:"mueres",fr:"matin"},
{l:7,k:"v",lb:"owes",fr:"soir"},{l:7,k:"v",lb:"Méindeg",fr:"lundi"},
{l:7,k:"v",lb:"Freideg",fr:"vendredi"},{l:7,k:"v",lb:"Sonndeg",fr:"dimanche"},
{l:7,k:"g",lb:"Wéi vill Auer ass et?",fr:"Quelle heure ?"},
{l:7,k:"p",lb:"Ech ginn um aacht Auer schaffen",fr:"À 8h au travail"},
// 8 — Déplacement
{l:8,k:"v",lb:"an",fr:"dans"},{l:8,k:"v",lb:"op",fr:"sur"},
{l:8,k:"v",lb:"bei",fr:"chez"},{l:8,k:"g",lb:"Déplacement = Akkusativ",fr:"Ech ginn an d'Bett"},
{l:8,k:"g",lb:"Position = Dativ",fr:"Ech schlofen an engem Bett"},
{l:8,k:"p",lb:"Ech gi bei de Bäcker",fr:"Chez le boulanger"},
// 9 — Chrëschtdag
{l:9,k:"v",lb:"de Wanter",fr:"hiver"},{l:9,k:"v",lb:"d'Fréijoer",fr:"printemps"},
{l:9,k:"v",lb:"de Summer",fr:"été"},{l:9,k:"v",lb:"de Schnéi",fr:"neige"},
{l:9,k:"p",lb:"Schéi Chrëschtdeeg!",fr:"Joyeux Noël !"},
{l:9,k:"p",lb:"E schéint neit Joer!",fr:"Bonne année !"},
// 10 — Adjectifs
{l:10,k:"g",lb:"En ale Mann",fr:"Un vieil homme"},
{l:10,k:"g",lb:"Eng grouss Fra",fr:"Une grande femme"},
{l:10,k:"g",lb:"fir ze + Infinitif",fr:"pour + infinitif"},
{l:10,k:"v",lb:"rout",fr:"rouge"},{l:10,k:"v",lb:"schwaarz",fr:"noir"},
{l:10,k:"v",lb:"gréng",fr:"vert"},{l:10,k:"v",lb:"grouss",fr:"grand"},
{l:10,k:"p",lb:"Ech ginn an de Park fir ze spillen",fr:"Pour jouer"},
// 11 — Prononciation
{l:11,k:"g",lb:"a redoublé = long",fr:"maachen"},
{l:11,k:"g",lb:"éi = 'veille'",fr:"schéin"},{l:11,k:"g",lb:"ei/ai = 'paille'",fr:"schei"},
{l:11,k:"g",lb:"ë = 'je'",fr:"Lëtzebuerg"},{l:11,k:"g",lb:"ou = 'je'",fr:"frou"},
{l:11,k:"g",lb:"ch après a,o,u",fr:"Buch"},{l:11,k:"g",lb:"ch après e,i,ä",fr:"richteg"},
// 12 — De Beruff
{l:12,k:"v",lb:"de Bäcker",fr:"boulanger"},{l:12,k:"v",lb:"de Metzler",fr:"boucher"},
{l:12,k:"v",lb:"den Dokter",fr:"docteur"},{l:12,k:"v",lb:"de Coiffeur",fr:"coiffeur"},
{l:12,k:"v",lb:"den Affekot",fr:"avocat"},{l:12,k:"v",lb:"de Kach",fr:"cuisinier"},
{l:12,k:"p",lb:"Wat fir e Beruff hues du?",fr:"Quel métier ?"},
{l:12,k:"p",lb:"Ech schaffen an engem Büro",fr:"Bureau en ville"},
// 13 — Imperativ
{l:13,k:"g",lb:"Imperatif sing. = radical",fr:"lafen → laf!"},
{l:13,k:"g",lb:"Imperatif plur. = radical+t",fr:"lafen → laaft!"},
{l:13,k:"g",lb:"sinn → sief/sidd",fr:"être"},{l:13,k:"g",lb:"goen → géi/gitt",fr:"aller"},
{l:13,k:"p",lb:"Schwätz net esou haart!",fr:"Ne parle pas si fort !"},
// 14 — Plural
{l:14,k:"g",lb:"d'Kand → d'Kanner",fr:"enfant → enfants"},
{l:14,k:"g",lb:"de Mann → d'Männer",fr:"homme → hommes"},
{l:14,k:"g",lb:"den Apel → d'Äppel",fr:"pomme → pommes"},
{l:14,k:"g",lb:"d'Haus → d'Haiser",fr:"maison → maisons"},
{l:14,k:"v",lb:"lénks",fr:"gauche"},{l:14,k:"v",lb:"riets",fr:"droite"},
{l:14,k:"v",lb:"riichtaus",fr:"tout droit"},
// 15 — Dokter
{l:15,k:"v",lb:"de Kapp",fr:"tête"},{l:15,k:"v",lb:"den Hals",fr:"gorge"},
{l:15,k:"v",lb:"den Aarm",fr:"bras"},{l:15,k:"v",lb:"de Bauch",fr:"ventre"},
{l:15,k:"v",lb:"d'Been",fr:"jambe"},{l:15,k:"v",lb:"de Fouss",fr:"pied"},
{l:15,k:"v",lb:"d'Spidol",fr:"hôpital"},{l:15,k:"v",lb:"d'Gripp",fr:"grippe"},
{l:15,k:"p",lb:"Ech ruffen un fir e Rendez-vous",fr:"J'appelle pour un RDV"},
{l:15,k:"p",lb:"Ech hunn de Kapp wéi",fr:"Mal à la tête"},
{l:15,k:"p",lb:"Ech hu Féiwer",fr:"Fièvre"},
// 16 — Possessifs
{l:16,k:"g",lb:"mäin/meng",fr:"mon/ma"},{l:16,k:"g",lb:"däin/deng",fr:"ton/ta"},
{l:16,k:"g",lb:"säin/seng",fr:"son/sa"},{l:16,k:"g",lb:"eisen/eis",fr:"notre/nos"},
{l:16,k:"p",lb:"Meng Mamm huet 56 Joer",fr:"Ma mère a 56 ans"},
{l:16,k:"p",lb:"Wou ass däin Auto?",fr:"Ta voiture ?"},
// 17 — Passé
{l:17,k:"g",lb:"ge + radical + t",fr:"participe passé"},
{l:17,k:"g",lb:"hunn imparfait",fr:"ech hat · du has · hien hat"},
{l:17,k:"g",lb:"sinn imparfait",fr:"ech war · du waars · hien war"},
{l:17,k:"g",lb:"sinn + déplacement",fr:"Ech si gefall"},
{l:17,k:"g",lb:"hunn + autres",fr:"Ech hu gelaacht"},
{l:17,k:"p",lb:"Ech krut e Kado",fr:"J'ai reçu un cadeau"},
{l:17,k:"p",lb:"Hatt war vill ze spéit",fr:"Elle était en retard"},
// 18 — Mat Kanner
{l:18,k:"g",lb:"gär hunn = aimer",fr:"Ech hunn dech gär"},
{l:18,k:"p",lb:"Ech hunn dech gär",fr:"Je t'aime"},
{l:18,k:"v",lb:"d'Spillschoul",fr:"école maternelle"},
{l:18,k:"v",lb:"de Lycée",fr:"lycée"},
{l:18,k:"v",lb:"de Schoulmeeschter",fr:"instituteur"},
{l:18,k:"g",lb:"sech freeën",fr:"se réjouir"},
// 19 — Adverbes
{l:19,k:"g",lb:"ëmmer",fr:"toujours"},{l:19,k:"g",lb:"oft, dacks",fr:"souvent"},
{l:19,k:"g",lb:"heiansdo",fr:"parfois"},{l:19,k:"g",lb:"ni",fr:"jamais"},
{l:19,k:"g",lb:"schonn",fr:"déjà"},{l:19,k:"g",lb:"eréischt",fr:"seulement"},
{l:19,k:"p",lb:"Ech gi meeschtens um 11 Auer schlofen",fr:"Souvent à 11h"},
// 20 — Akafen
{l:20,k:"v",lb:"e Kilo",fr:"kilo"},{l:20,k:"v",lb:"e Pond",fr:"500g"},
{l:20,k:"v",lb:"eng Dosen",fr:"douzaine"},{l:20,k:"v",lb:"kafen",fr:"acheter"},
{l:20,k:"v",lb:"bezuelen",fr:"payer"},{l:20,k:"v",lb:"deier",fr:"cher"},
{l:20,k:"v",lb:"bëlleg",fr:"bon marché"},{l:20,k:"v",lb:"d'Gromper",fr:"pomme de terre"},
{l:20,k:"p",lb:"Ech hätt gär e Kilo Wuerzelen",fr:"Je voudrais 1kg de carottes"},
{l:20,k:"p",lb:"Kann ech mat der Kaart bezuelen?",fr:"Payer par carte ?"},
// 21 — Futur
{l:21,k:"g",lb:"Futur = présent + temps",fr:"Muer ginn ech"},
{l:21,k:"g",lb:"méi...wéi",fr:"plus...que"},{l:21,k:"g",lb:"esou...wéi",fr:"aussi...que"},
{l:21,k:"p",lb:"Muer ginn ech bei den Dokter",fr:"Demain"},
{l:21,k:"p",lb:"Du bass méi grouss wéi ech",fr:"Plus grand"},
{l:21,k:"v",lb:"d'Hëft",fr:"hanche"},{l:21,k:"v",lb:"de Knéchel",fr:"cheville"},
{l:21,k:"v",lb:"de Réck",fr:"dos"},
// 22 — Akkusativ
{l:22,k:"g",lb:"Akkusativ = COD",fr:"Ech kafen en Haus"},
{l:22,k:"g",lb:"Dativ = COI",fr:"Ech kafen dem Claudia en Auto"},
{l:22,k:"g",lb:"de Mann → dem Mann",fr:"Défini masc"},
{l:22,k:"g",lb:"Akk prép.",fr:"bis · géint · duerch · ouni · fir · ëm"},
{l:22,k:"g",lb:"Dat prép.",fr:"aus · zanter · mat · vun · trotz · no"},
{l:22,k:"p",lb:"Ech wunnen zanter dräi Joer",fr:"Depuis 3 ans"},
// 23 — Lieseck Têtelbierg
{l:23,k:"v",lb:"de Ritter",fr:"chevalier"},{l:23,k:"v",lb:"de Paschtouer",fr:"prêtre"},
{l:23,k:"v",lb:"d'Buerg",fr:"château fort"},{l:23,k:"v",lb:"d'Stëmm",fr:"voix"},
{l:23,k:"v",lb:"verschwannen",fr:"disparaître"},
// 24 — Reesen
{l:24,k:"v",lb:"Europa",fr:"Europe"},{l:24,k:"v",lb:"d'Valise",fr:"valise"},
{l:24,k:"v",lb:"de Pass",fr:"passeport"},{l:24,k:"v",lb:"de Fluch",fr:"vol"},
{l:24,k:"v",lb:"d'Zëmmer",fr:"chambre"},{l:24,k:"v",lb:"buchen",fr:"réserver"},
{l:24,k:"p",lb:"Ech hunn eng Vakanz gebucht!",fr:"Réservé vacances !"},
{l:24,k:"p",lb:"Mäi Fluch geet den éischte Mee",fr:"Vol le 1er mai"},
// 25 — Kleeder
{l:25,k:"v",lb:"den Hutt",fr:"chapeau"},{l:25,k:"v",lb:"d'Mutz",fr:"bonnet"},
{l:25,k:"v",lb:"de Pullover",fr:"pullover"},{l:25,k:"v",lb:"d'Hiem",fr:"chemise"},
{l:25,k:"v",lb:"de Mantel",fr:"manteau"},{l:25,k:"v",lb:"d'Box",fr:"pantalon"},
{l:25,k:"v",lb:"de Schong",fr:"chaussure"},
{l:25,k:"p",lb:"Do deng Mutz un! Et ass kal",fr:"Mets ton bonnet !"},
// 26 — Exercicer I
{l:26,k:"v",lb:"de Coiffeur",fr:"coiffeur"},{l:26,k:"v",lb:"d'Serveuse",fr:"serveuse"},
{l:26,k:"v",lb:"de Buschauffeur",fr:"chauffeur bus"},
{l:26,k:"g",lb:"Nee, keen/keng",fr:"Ech hu keen Honger · keng Déieren"},
{l:26,k:"p",lb:"Hie schneit Hoer → Coiffeur",fr:"Coupe → coiffeur"},
// 27 — Conditionnel
{l:27,k:"g",lb:"hunn cond.",fr:"ech hätt · du häss"},
{l:27,k:"g",lb:"sinn cond.",fr:"ech wier · du wiers"},
{l:27,k:"g",lb:"goen cond.",fr:"ech géif · du géifs"},
{l:27,k:"v",lb:"de Läffel",fr:"cuillère"},{l:27,k:"v",lb:"d'Forschett",fr:"fourchette"},
{l:27,k:"v",lb:"d'Messer",fr:"couteau"},{l:27,k:"v",lb:"den Teller",fr:"assiette"},
{l:27,k:"p",lb:"Ech hätt gär e Kaffi",fr:"Je voudrais un café"},
// 28 — Biller ⭐
{l:28,k:"v",lb:"karéiert",fr:"à carreaux"},
{l:28,k:"v",lb:"geblummelt",fr:"motif fleurs"},
{l:28,k:"v",lb:"den Hannergrond",fr:"arrière-plan"},
{l:28,k:"v",lb:"d'Luucht",fr:"lampe"},{l:28,k:"v",lb:"de Mound",fr:"lune"},
{l:28,k:"v",lb:"de Stär",fr:"étoile"},{l:28,k:"v",lb:"de Séi",fr:"lac"},
{l:28,k:"v",lb:"de Bierg",fr:"montagne"},{l:28,k:"v",lb:"den Himmel",fr:"ciel"},
{l:28,k:"p",lb:"Um Bild gesäit een eng Landschaft",fr:"Sur l'image, on voit un paysage"},
{l:28,k:"p",lb:"Et ass däischter an de Mound schéngt",fr:"Il fait noir et la lune brille"},
{l:28,k:"p",lb:"An der Mëtt vum Bild ass e Séi",fr:"Au milieu un lac"},
{l:28,k:"p",lb:"D'Mia ass eng jonk Fra",fr:"Mia est une jeune femme"},
{l:28,k:"p",lb:"Seng Ae si brong",fr:"Ses yeux sont bruns"},
// 29 — Famill
{l:29,k:"v",lb:"d'Elteren",fr:"parents"},{l:29,k:"v",lb:"d'Mamm",fr:"mère"},
{l:29,k:"v",lb:"de Papp",fr:"père"},{l:29,k:"v",lb:"d'Duechter",fr:"fille"},
{l:29,k:"v",lb:"de Bouf",fr:"garçon"},{l:29,k:"v",lb:"d'Schwëster",fr:"sœur"},
{l:29,k:"v",lb:"de Brudder",fr:"frère"},{l:29,k:"v",lb:"d'Grousselteren",fr:"grands-parents"},
{l:29,k:"v",lb:"d'Tatta",fr:"tante"},{l:29,k:"v",lb:"de Monni",fr:"oncle"},
{l:29,k:"g",lb:"Superlatif am + adj + sten",fr:"am gréissten · am beschten"},
{l:29,k:"p",lb:"Sonndes ësst d'ganz Famill zesummen",fr:"Dimanches ensemble"},
// 30 — Lieseck Delarü
{l:30,k:"v",lb:"däischter",fr:"sombre"},{l:30,k:"v",lb:"hell",fr:"clair"},
{l:30,k:"v",lb:"nëmmen",fr:"seulement"},{l:30,k:"v",lb:"den Honger",fr:"faim"},
{l:30,k:"v",lb:"geféierlech",fr:"dangereux"},
// 31 — Impfungen
{l:31,k:"v",lb:"d'Impfung",fr:"vaccin"},{l:31,k:"v",lb:"den Impfstoff",fr:"vaccin"},
{l:31,k:"v",lb:"den Hausdokter",fr:"généraliste"},{l:31,k:"v",lb:"d'Piqûre",fr:"piqûre"},
{l:31,k:"v",lb:"wéidoen",fr:"faire mal"},
{l:31,k:"g",lb:"sech impfe loossen",fr:"se faire vacciner"},
{l:31,k:"p",lb:"D'Piqûre huet net weigedoen",fr:"Pas eu mal"},
// 32 — Modalverben
{l:32,k:"g",lb:"däerfen",fr:"pouvoir (droit)"},{l:32,k:"g",lb:"kënnen",fr:"pouvoir"},
{l:32,k:"g",lb:"mussen",fr:"devoir"},{l:32,k:"g",lb:"sollen",fr:"devoir (censé)"},
{l:32,k:"g",lb:"wëllen",fr:"vouloir"},
{l:32,k:"p",lb:"Ech wëll en neien Auto kafen",fr:"Nouvelle voiture"},
{l:32,k:"p",lb:"De Mario ass ganz grouss",fr:"Très grand"},
// 33 — Kachen
{l:33,k:"v",lb:"kachen",fr:"cuisiner"},{l:33,k:"v",lb:"baken",fr:"cuire (four)"},
{l:33,k:"v",lb:"broden",fr:"cuire (poêle)"},{l:33,k:"v",lb:"schneiden",fr:"couper"},
{l:33,k:"v",lb:"schielen",fr:"éplucher"},{l:33,k:"v",lb:"wäschen",fr:"laver"},
{l:33,k:"v",lb:"mëschen",fr:"mélanger"},
{l:33,k:"p",lb:"Mamm, wat gëtt et haut z'iessen?",fr:"À manger ?"},
{l:33,k:"p",lb:"Et richt esou gutt",fr:"Ça sent bon"},
// 34 — Exercicer II
{l:34,k:"g",lb:"grouss → kleng",fr:"grand → petit"},
{l:34,k:"g",lb:"jonk → al",fr:"jeune → vieux"},
{l:34,k:"g",lb:"laang → kuerz",fr:"long → court"},
{l:34,k:"g",lb:"kal → waarm",fr:"froid → chaud"},
{l:34,k:"p",lb:"Wou wars du?",fr:"Où étais-tu ?"},
{l:34,k:"p",lb:"Mir konnten net kommen",fr:"Ne pouvions pas venir"},
// 35 — Wieder
{l:35,k:"v",lb:"d'Wieder",fr:"temps"},{l:35,k:"v",lb:"de Wand",fr:"vent"},
{l:35,k:"v",lb:"d'Sonn",fr:"soleil"},{l:35,k:"v",lb:"de Reen",fr:"pluie"},
{l:35,k:"v",lb:"de Schnéi",fr:"neige"},{l:35,k:"v",lb:"de Stuerm",fr:"tempête"},
{l:35,k:"p",lb:"Et reent",fr:"Il pleut"},{l:35,k:"p",lb:"D'Sonn schéngt",fr:"Soleil brille"},
{l:35,k:"p",lb:"Et ass kal dobaussen",fr:"Il fait froid dehors"},
// 36 — Lieseck Melusina
{l:36,k:"v",lb:"viru laanger Zäit",fr:"il y a longtemps"},
{l:36,k:"v",lb:"de Grof",fr:"comte"},{l:36,k:"v",lb:"d'Sireen",fr:"sirène"},
{l:36,k:"v",lb:"bestueden",fr:"épouser"},{l:36,k:"v",lb:"d'Buerg",fr:"château fort"},
// 37 — Relativsätz
{l:37,k:"g",lb:"männlech : deen",fr:"relatif masc"},
{l:37,k:"g",lb:"weiblech : déi",fr:"relatif fém"},
{l:37,k:"g",lb:"sächlech : dat",fr:"relatif neutre"},
{l:37,k:"p",lb:"De Kaffi, deen ech kaf hunn, ass net gutt",fr:"Le café que j'ai acheté"},
{l:37,k:"p",lb:"D'Kaz, déi meng Mamm fiddert, ass déck",fr:"Le chat que ma mère nourrit"},
// 38 — Auto
{l:38,k:"v",lb:"de Capot",fr:"capot"},{l:38,k:"v",lb:"de Pneu",fr:"pneu"},
{l:38,k:"v",lb:"d'Mall",fr:"coffre"},{l:38,k:"v",lb:"d'Brems",fr:"frein"},
{l:38,k:"v",lb:"d'Strooss",fr:"route"},{l:38,k:"v",lb:"de Verkéier",fr:"trafic"},
{l:38,k:"v",lb:"fueren",fr:"conduire"},{l:38,k:"v",lb:"tanken",fr:"faire le plein"},
{l:38,k:"p",lb:"Fuer net esou schnell!",fr:"Ne conduis pas si vite !"},
{l:38,k:"p",lb:"Bei rout muss ee stoe bleiwen",fr:"Au rouge s'arrêter"}
]
};